#cloud-config
users:
  - name: ${username}
    lock_passwd: False
    groups: [sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_key}
chpasswd: { expire: False }
ssh_pwauth: True
package_update: true
packages:
  - curl
  - git
runcmd:
  - echo 'Password login enabled for lab. Disable after use.' > /etc/motd.d/99-lab.txt
  - hostnamectl set-hostname ${vm_name}
