#cloud-config
hostname: openstack-controller
manage_etc_hosts: true

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    passwd: "${ubuntu_password_hash}"
    ssh_authorized_keys:
      - ${ssh_key}
    lock_passwd: false
  - name: stack
    groups: sudo
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    passwd: "${ubuntu_password_hash}"
    ssh_authorized_keys:
      - ${ssh_key}


package_update: true
package_upgrade: true